### ISSUE TITLE
abi-compliance-check dies after consuming 28 GB of virtual memory

### ISSUE THREAD

**Issue by michihenning** [lvc/abi-compliance-checker#24]
I'm seeing this with version 1.99.9-2 on Ubuntu Wily with gcc 5.2.1.

I'm comparing ABIs for a large C++ library. Dumping the new ABI works fine, but comparing against the old one causes abi-compliance-checker to consume more and more memory until it finally dies at around 28 GB of virtual memory.

Here are links to the files. (I can't attach those files because they are the wrong type.)

Old ABI dump: https://www.dropbox.com/s/fh7bk0kmj5fb3qd/libunity-scopes_1.0.0.abi.tar.gz?dl=0
New ABI dump: https://www.dropbox.com/s/tsuaay3xfvqy390/libunity-scopes_1.0.2.abi.tar.gz?dl=0
XML file: https://www.dropbox.com/s/r8j5yltdsl8apsr/abi.xml?dl=0

I'd appreciate any help with this, abi-compliance-checker is a really crucial tool for us.

**Comment by aponomarenko** [comment]
Hello,

Thank you for reporting the issue.

The issue is reproduced and fixed. Please checkout the latest version of the tool.

Also please consider to use the new abi-dumper tool (https://github.com/lvc/abi-dumper) in order to create ABI dumps for your library. The usage example is here: https://wiki.openssl.org/index.php/Binary_Compatibility. It's more reliable because it doesn't require compilation of header files.

**Comment by michihenning** [comment]
Wow, I'm blown away, thank you so much for the super-fast fix! I'm currently switching over to abi-dumper. Will re-test with the installed version of abi-compliance-checker 1.99.14 on Xenial (to see whether there is still a crash that way). Otherwise, I guess we'll have to apply a distro patch to get fixed checker into Xenial.

Thanks again for your help!

**Comment by michihenning** [comment]
I've just tried with the latest version, and all is well now. Thanks again!
