### ISSUE TITLE
Could we add a root label for the XML descriptor file ?

### ISSUE THREAD

**Issue by zhangfan5494** [lvc/abi-compliance-checker#29]
Now I try to use python library to generate the XML descriptor file automatically, but it seems that they need the XML file have a root label, I want to know whether we could add a root xml label for the descriptor file or not ?

**Comment by aponomarenko** [comment]
Hello,

You can add any root label (tag) because the tool parses the descriptor by regular expressions for particular sub-tags like headers, libs, etc.

Also please note that you can avoid analysis of header files (and thus creating of any descriptors) by using the abi-dumper tool: https://github.com/lvc/abi-dumper

Thank you.

**Comment by zhangfan5494** [comment]
All right, got it~
