### ISSUE TITLE
Source Compatible or not? 

### ISSUE THREAD

**Issue by zhuda** [lvc/abi-compliance-checker#51]
@lvc 

Suppose I a module and with following SDK headers:

SDK
  |--whatever.h

Then in next build I changed it's header file's location with adding a sub folder.
SDK
  |--Visual
     ---|-whatever.h

Do  you think this is source compatible? 
From Thiago Macieira's document [Source compatibility](https://events.linuxfoundation.org/sites/events/files/slides/Binary_Compatibility_for_library_devs.pdf) means:
>Two libraries are source compatible with each other if:
• Source code written against one will compile without changes
against the other.

However when using ABI checker the tool reported this case is source compatible. Is this right? or I used the tool incorrectly?

**Comment by lvc** [comment]
This particular compatibility issue can be fixed by a compilation flag (addition of the include path). But in general moving or renaming of a header file can break source compatibility. The tool currently doesn't check it. Please use `pkgdiff` tool on your library source packages (or on install trees with the help of the `-d` option) to detect added/removed and renamed files of a project.

Thank you.

**Comment by zhuda** [comment]
Thanks for the information. I can take a look the pdgdiff and see how it works. did you have any recommendation about similar tools on Windows platform?

**Comment by zhuda** [comment]
Find some simple script can do the package compare so I closed this issue.
